base_model: meta-llama/Meta-Llama-3-8B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

rl: sppo
rl_beta: 0.1
datasets:
  - path: orion-research/Aura-SPPO-Iter1_score
    type: chatml.sppo_argilla_chat
dataset_prepared_path:
val_set_size: 0

output_dir: ./outputs/out/Meta-Llama-3-8B-Instruct-SPPO-Iter1
dataset_prepared_path: last_run_prepared

adapter: qlora
lora_model_dir:

sequence_len: 1024
sample_packing: false
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
peft_use_dora: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2.0e-4

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

save_safetensors: true
warmup_steps: 50
evals_per_epoch: 1
eval_max_new_tokens: 128
eval_table_size:
save_steps: 100
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<|end_of_text|>"
