name: E2E
on:
  pull_request:
  workflow_dispatch:

jobs:
  e2e-test:
    name: E2E Tests
    runs-on: [self-hosted, gpu, e2e]
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10"]
    timeout-minutes: 10

    steps:
      - name: Wait for pytest and pre-commit to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'E2E Tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          pip3 install -e .
          pip3 install flash-attn
          pip3 install -r requirements-tests.txt

      - name: Run e2e tests
        run: |
          pytest tests/e2e/
