name: E2E
on:
  # check on push/merge to main, PRs, and manual triggers
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  e2e-test:
    name: E2E Tests
    runs-on: [self-hosted, gpu, e2e]
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10"]
    timeout-minutes: 20
    permissions:
      actions: read

    steps:
      - name: Wait for pytest and pre-commit to succeed
        uses: yogeshlonkar/wait-for-jobs@v0
        with:
          ref: ${{ github.ref }}
          jobs: 'pre-commit,pre-commit'
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          interval: 60000
          ttl: '15'

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          pip3 install -e .
          pip3 install flash-attn
          pip3 install -r requirements-tests.txt

      - name: Run e2e tests
        run: |
          pytest tests/e2e/
